name: CI-build-and-test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Install Pods
      run: pod install
      
    - name: Build and test
      run: xcodebuild clean build test -workspace "Test CI.xcworkspace" -scheme "Test CI" -sdk "iphonesimulator14.4" -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.4'
