name: CI-build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Pods
      run: pod install

    # - name: Select Xcode 12
    #   run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    # - name: Build and test iOS 14
    #   run: xcodebuild clean build test -workspace "Test CI.xcworkspace" -scheme "Test CI" -sdk "iphonesimulator14.4" -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.4'

    - name: Select Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.7.app

    - name: Build and test iOS 13
      run: xcodebuild clean build test -workspace "Test CI.xcworkspace" -scheme "Test CI" -sdk "iphonesimulator13.7" -destination 'platform=ABC,name=iPhone 8,OS=13.7'